server:
  port: 8080
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb  # Base de datos en memoria
    # url: jdbc:h2:file:/data/orderdb # Para persistencia en archivo
    username: sm
    password: sm
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5  # Tamaño reducido para H2

  h2:
    console:
      enabled: true  # Habilita la consola web
      path: /h2-console  # Ruta de acceso
      settings:
        web-allow-others: false  # Seguridad

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true